version: '3'

services:
   nginx:
    image: nginx:1.18.0
    container_name: cost_nginx
    volumes:
     - ./app:/usr/share/nginx/html
     - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx_logs/nginx-access.log:/var/log/nginx/access.log
     - ./nginx_logs/nginx-error.log:/var/log/nginx/error.log
    restart: always
    ports:
      - 80:80
      - 443:443
